#!/bin/bash
#
#SBATCH --job-name="Process_New_Ablate_Data"
#SBATCH -o Process_New_Ablate_Data.out
#SBATCH -e Process_New_Ablate_Data.err
#SBATCH --mail-user=dwyerdei@buffalo.edu
#SBATCH --mail-type=end
#SBATCH --cluster=ub-hpc
#SBATCH --partition=debug #general-compute
#SBATCH --qos=debug #general-compute
#SBATCH --mem=100G
#SBATCH --nodes=2
#SBATCH --ntasks-per-node=30
#SBATCH --time=00:15:00

. wrangle_all_ablate_data-ccr.sh
